### ISSUE TITLE
No key error

### ISSUE THREAD

**Issue by Johnqxy** [Seb-B-364/BlenderMapDEM#1]
here is my message 
Blender 4.0.2 (hash 9be62e85b727 built 2023-12-05 13:01:12)
Read prefs: "C:\Users\robo\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\renderDEM.py", line 99, in renderDEM
    plane = bpy.data.objects['Plane']
KeyError: 'bpy_prop_collection[key]: key "Plane" not found'

Blender quit

**Comment by Seb-geospatial** [comment]
Hi, i'm suspecting this is probably due to changes in the Blender bpy package as of Blender 4.0.2, as BlenderMapDEM is only tested and working as of Blender 4.0.1. I will attempt to address any changes Blender has made to how their python package works and update this package to be current.

Thank you for bringing this issue to my attention.

**Comment by Seb-geospatial** [comment]
After updating I am unable to reproduce your error, i have updated my Blender installation to the newest version (4.0.2) and after running the following script to produce a rendered hillshade image from existing DEM images i have saved it appears nothing has broken on my end:

```
from BlenderMapDEM import *

# Specifying paths of blender.exe, input DEM image, and output rendered image
blender = 'C:/Program Files/Blender Foundation/Blender 4.0/blender.exe'
DEM =  'C:/Home/Documents/Coding/Python/BarbadosDEM_image.png'
output = 'C:/Home/Documents/Coding/Python/render.png'

# Use renderDEM to run blender from within this python script
renderDEM(blender_dir = blender, dem_dir = DEM, output_dir = output)
```

Would you provide some more context into how you are using the package, are you running it from a script such as the one above? Is your Blender startup scene any different from default? The error suggests that Blender cannot find a Plane object in the scene however it should exist if the previous lines of code did not error.

**Comment by Seb-geospatial** [comment]
This issue is going to be closed due to inability to reproduce the error.
